# Import Dependences

In [1]:
import pandas as pd
import numpy as np

# Load the data into dataframes

In [2]:
movies_df = pd.read_csv("./Resources/merged_larger_movies_processed.csv")
directors_df = pd.read_csv("./Resources/merged_larger_director_data_avg.csv", encoding='utf-8')
writers_df = pd.read_csv("./Resources/merged_larger_writer_data_avg.csv", encoding='utf-8') 
actors_df = pd.read_csv("./Resources/merged_larger_actor_data_avg.csv", encoding='utf-8') 
# Get rid of the index column in primary DF
movies_df = movies_df[['tconst', 'averageRating', 'OMDB_Title', 
                             'OMDB_Rated', 'OMDB_Runtime', 'OMDB_Genre', 'OMDB_Director', 'OMDB_Writer', 
                             'OMDB_Actors', 'OMDB_Language', 'OMDB_Country', 'OMDB_Metascore', 'OMDB_imdbRating',
                             'OMDB_imdbVotes', 'OMDB_BoxOffice', 'OMDB_Production', 'ReleaseYear', 'ReleaseMonth']]

In [5]:
movies_df.head()

,tconst,averageRating,OMDB_Title,OMDB_Rated,OMDB_Runtime,OMDB_Genre,OMDB_Director,OMDB_Writer,OMDB_Actors,OMDB_Language,OMDB_Country,OMDB_Metascore,OMDB_imdbRating,OMDB_imdbVotes,OMDB_BoxOffice,OMDB_Production,ReleaseYear,ReleaseMonth
0,tt0013274,6.8,Istoriya grazhdanskoy voyny,unknown,94.0,Documentary,"Nikolai Izvolov, Dziga Vertov",NaN,NaN,None,Soviet Union,NaN,NaN,58.0,NaN,NaN,2022.0,5.0
1,tt0015414,5.2,La tierra de los toros,unknown,60.0,NaN,Musidora,NaN,"Antonio Cañero, Musidora",None,"Spain, France",NaN,6.6,16.0,NaN,NaN,NaN,NaN
2,tt0015724,6.1,Dama de noche,unknown,102.0,"Drama, Mystery, Romance",Eva López Sánchez,"Eva López Sánchez, David Martin del Campo","Rafael Sánchez Navarro, Cecilia Toussaint, Mig...",Spanish,Mexico,NaN,5.8,27.0,NaN,NaN,1993.0,3.0
3,tt0035423,6.4,Kate & Leopold,teens,118.0,"Comedy, Fantasy, Romance",James Mangold,"Steven Rogers, James Mangold","Meg Ryan, Hugh Jackman, Liev Schreiber","English, French",United States,44.0,6.4,87977.0,47121859.0,NaN,2001.0,12.0
4,tt0036606,6.5,"Another Time, Another Place",adults,118.0,"Drama, War",Michael Radford,"Jessie Kesson, John Francis Lane, Michael Radford","Phyllis Logan, Giovanni Mauriello, Gianluca Fa...","English, Italian",United Kingdom,NaN,6.5,338.0,NaN,NaN,1984.0,5.0

In [6]:
directors_df.head()

,Director,Instances,Total_Box_Office,Total_Production_Budget,Total_Metascore,Total_IMDB_Rating,Average_Box_Office,Average_IMDB_Rating,Success_Metric
0,Nikolai Izvolov,1,NaN,NaN,NaN,6.8,NaN,6.800000,NaN
1,Dziga Vertov,1,NaN,NaN,NaN,6.8,NaN,6.800000,NaN
2,Musidora,1,NaN,NaN,NaN,5.2,NaN,5.200000,NaN
3,Eva López Sánchez,3,NaN,NaN,NaN,18.1,NaN,6.033333,NaN
4,James Mangold,12,1.074486e+09,NaN,769.0,86.0,8.954048e+07,7.166667,8.957476

# Pull in Director Average Box Office, IMDB Rating, and Combined Score

In [3]:
# Loop through every row of the movies_df
for index, row in movies_df.iterrows():
    movie_directors = row['OMDB_Director']
    # Only take action if the directors cell is populated with a string
    if isinstance(movie_directors, str) and movie_directors != "" :
        # Convert the comma separated list of directors into a list
        director_list = movie_directors.split(", ")
        # Set lists to store the ratings for a given row
       # boxes = []
        ratings = []
       # scores = []
        # Iterate through the each director in the lsit
        for d in director_list:
            # Collect the values for the given director
            #d_box = directors_df.loc[directors_df['Director'] == d, 'Average_Box_Office'].iloc[0]
            d_rating = directors_df.loc[directors_df['Director'] == d, 'Average_IMDB_Rating'].iloc[0]
            #d_score = directors_df.loc[directors_df['Director'] == d, 'Success_Metric'].iloc[0]

            # Only populate the list if a number (i.e., not NaN) to avoid creating NaN if 1 out of 6 is NaN
            #if d_box > 0: 
                #boxes.append(d_box)
            if d_rating > 0: 
                ratings.append(d_rating)
            #if d_score > 0: 
                #scores.append(d_score)
        # Populate the DataFrame with the average across the listed directors
        #if boxes != []:
           # directors_box = round(np.average(boxes),2)
            #movies_df.loc[index,'Director_Avg_Box'] = directors_box
        if ratings != []:
            directors_rating = round(np.average(ratings),2)
            movies_df.loc[index,'Director_Avg_Rating'] = directors_rating
       # if scores != []:
            #directors_score = round(np.average(scores),2)
            #movies_df.loc[index,'Director_Score'] = directors_score

movies_df.head()

,tconst,averageRating,OMDB_Title,OMDB_Rated,OMDB_Runtime,OMDB_Genre,OMDB_Director,OMDB_Writer,OMDB_Actors,OMDB_Language,OMDB_Country,OMDB_Metascore,OMDB_imdbRating,OMDB_imdbVotes,OMDB_BoxOffice,OMDB_Production,ReleaseYear,ReleaseMonth,Director_Avg_Rating
0,tt0013274,6.8,Istoriya grazhdanskoy voyny,unknown,94.0,Documentary,"Nikolai Izvolov, Dziga Vertov",NaN,NaN,None,Soviet Union,NaN,NaN,58.0,NaN,NaN,2022.0,5.0,6.80
1,tt0015414,5.2,La tierra de los toros,unknown,60.0,NaN,Musidora,NaN,"Antonio Cañero, Musidora",None,"Spain, France",NaN,6.6,16.0,NaN,NaN,NaN,NaN,5.20
2,tt0015724,6.1,Dama de noche,unknown,102.0,"Drama, Mystery, Romance",Eva López Sánchez,"Eva López Sánchez, David Martin del Campo","Rafael Sánchez Navarro, Cecilia Toussaint, Mig...",Spanish,Mexico,NaN,5.8,27.0,NaN,NaN,1993.0,3.0,6.03
3,tt0035423,6.4,Kate & Leopold,teens,118.0,"Comedy, Fantasy, Romance",James Mangold,"Steven Rogers, James Mangold","Meg Ryan, Hugh Jackman, Liev Schreiber","English, French",United States,44.0,6.4,87977.0,47121859.0,NaN,2001.0,12.0,7.17
4,tt0036606,6.5,"Another Time, Another Place",adults,118.0,"Drama, War",Michael Radford,"Jessie Kesson, John Francis Lane, Michael Radford","Phyllis Logan, Giovanni Mauriello, Gianluca Fa...","English, Italian",United Kingdom,NaN,6.5,338.0,NaN,NaN,1984.0,5.0,6.62

# Pull in Writer Average Box Office, IMDB Rating, and Combined Score

In [6]:
# Loop through every row of the movies_df
for index, row in movies_df.iterrows():
    if index%10000==0:
        print(f'working on index:{index}')
    movie_writers = row['OMDB_Writer']
    # Only take action if the directors cell is populated with a string
    if isinstance(movie_writers, str) and movie_writers != "" :
        # Convert the comma separated list of directors into a list
        writer_list = movie_writers.split(", ")
        # Set lists to store the ratings for a given row
        #boxes = []
        ratings = []
        #scores = []
        # Iterate through the each director in the lsit
        for w in writer_list:
            # Collect the values for the given director
            try:
                #w_box = writers_df.loc[writers_df['Writer'] == w, 'Average_Box_Office'].iloc[0]
                w_rating = writers_df.loc[writers_df['Writer'] == w, 'Average_IMDB_Rating'].iloc[0]
                #w_score = writers_df.loc[writers_df['Writer'] == w, 'Success_Metric'].iloc[0]
            except IndexError:
                w_rating = 0
            # Only populate the list if a number (i.e., not NaN) to avoid creating NaN if 1 out of 6 is NaN
            #if w_box > 0: 
                #boxes.append(w_box)
            if w_rating > 0: 
                ratings.append(w_rating)
            #if w_score > 0: 
                #scores.append(w_score)

        # Populate the DataFrame with the average across the listed directors
        #if boxes != []:
            #writers_box = round(np.average(boxes),2)
            #movies_df.loc[index,'Writer_Avg_Box'] = writers_box
        if ratings != []:
            writers_rating = round(np.average(ratings),2)
            movies_df.loc[index,'Writer_Avg_Rating'] = writers_rating
        #if scores != []:
            #writers_score = round(np.average(scores),2)
            #movies_df.loc[index,'Writer_Score'] = writers_score

movies_df.head()

working on index:0
working on index:10000
working on index:20000
working on index:30000
working on index:40000
working on index:50000
working on index:60000
working on index:70000
working on index:80000
working on index:90000
working on index:100000
working on index:110000
working on index:120000
working on index:130000
working on index:140000
working on index:150000
working on index:160000
working on index:170000
working on index:180000
working on index:190000
working on index:200000
working on index:210000
working on index:220000

,tconst,averageRating,OMDB_Title,OMDB_Rated,OMDB_Runtime,OMDB_Genre,OMDB_Director,OMDB_Writer,OMDB_Actors,OMDB_Language,...,OMDB_imdbRating,OMDB_imdbVotes,OMDB_BoxOffice,OMDB_Production,ReleaseYear,ReleaseMonth,Director_Avg_Rating,Writer_Avg_Rating,Writer_Avg_Box,Writer_Score
0,tt0013274,6.8,Istoriya grazhdanskoy voyny,unknown,94.0,Documentary,"Nikolai Izvolov, Dziga Vertov",NaN,NaN,None,...,NaN,58.0,NaN,NaN,2022.0,5.0,6.80,NaN,NaN,NaN
1,tt0015414,5.2,La tierra de los toros,unknown,60.0,NaN,Musidora,NaN,"Antonio Cañero, Musidora",None,...,6.6,16.0,NaN,NaN,NaN,NaN,5.20,NaN,NaN,NaN
2,tt0015724,6.1,Dama de noche,unknown,102.0,"Drama, Mystery, Romance",Eva López Sánchez,"Eva López Sánchez, David Martin del Campo","Rafael Sánchez Navarro, Cecilia Toussaint, Mig...",Spanish,...,5.8,27.0,NaN,NaN,1993.0,3.0,6.03,6.07,NaN,NaN
3,tt0035423,6.4,Kate & Leopold,teens,118.0,"Comedy, Fantasy, Romance",James Mangold,"Steven Rogers, James Mangold","Meg Ryan, Hugh Jackman, Liev Schreiber","English, French",...,6.4,87977.0,47121859.0,NaN,2001.0,12.0,7.17,6.86,64393725.76,8.14
4,tt0036606,6.5,"Another Time, Another Place",adults,118.0,"Drama, War",Michael Radford,"Jessie Kesson, John Francis Lane, Michael Radford","Phyllis Logan, Giovanni Mauriello, Gianluca Fa...","English, Italian",...,6.5,338.0,NaN,NaN,1984.0,5.0,6.62,6.50,NaN,NaN

# Pull in Actor/Actress Average Box Office, IMDB Rating, and Combined Score

In [ ]:
# Loop through every row of the movies_df
for index, row in movies_df.iterrows():
    if index%10000==0:
        print(f'working on index:{index}')
    movie_actors = row['OMDB_Actors']
    # Only take action if the directors cell is populated with a string
    if isinstance(movie_actors, str) and movie_actors != "" :
        # Convert the comma separated list of directors into a list
        actor_list = movie_actors.split(", ")
        # Set lists to store the ratings for a given row
        #boxes = []
        ratings = []
        #scores = []
        # Iterate through the each director in the lsit
        for a in actor_list:
            # Collect the values for the given director
            try:
                #a_box = actors_df.loc[actors_df['Actor'] == a, 'Average_Box_Office'].iloc[0]
                a_rating = actors_df.loc[actors_df['Actor'] == a, 'Average_IMDB_Rating'].iloc[0]
                #a_score = actors_df.loc[actors_df['Actor'] == a, 'Success_Metric'].iloc[0]
            except IndexError:
                a_rating = 0
            # Only populate the list if a number (i.e., not NaN) to avoid creating NaN if 1 out of 6 is NaN
            #if a_box > 0: 
                #boxes.append(a_box)
            if a_rating > 0: 
                ratings.append(a_rating)
            #if a_score > 0: 
                #scores.append(a_score)
        # Populate the DataFrame with the average across the listed directors
        #if boxes != []:
            #actors_box = round(np.average(boxes),2)
            #movies_df.loc[index,'Actor_Avg_Box'] = actors_box
        if ratings != []:
            actors_rating = round(np.average(ratings),2)
            movies_df.loc[index,'Actor_Avg_Rating'] = actors_rating
        #if scores != []:
            #actors_score = round(np.average(scores),2)
            #movies_df.loc[index,'Actor_Score'] = actors_score

movies_df.head()

working on index:0
working on index:10000
working on index:20000
working on index:30000
working on index:40000
working on index:50000
working on index:60000
working on index:70000
working on index:80000
working on index:90000
working on index:100000
working on index:110000
working on index:120000

In [8]:
movies_df.to_csv("./Resources/larger_merged_movies_people2numbers.csv")