# Import Dependences

In [1]:
import pandas as pd
import numpy as np

# Load the data into dataframes

In [2]:
movies_df = pd.read_csv("./Resources/movies_processed.csv")
directors_df = pd.read_csv("./Resources/director_data_avg.csv", encoding='utf-8')
writers_df = pd.read_csv("./Resources/writer_data_avg.csv", encoding='utf-8') 
actors_df = pd.read_csv("./Resources/actor_data_avg.csv", encoding='utf-8') 
# Get rid of the index column in primary DF
movies_df = movies_df[['Movie', 'ProductionBudget', 'DomesticGross','WorldwideGross', 'OMDB_Title', 
                             'OMDB_Rated', 'OMDB_Runtime', 'OMDB_Genre', 'OMDB_Director', 'OMDB_Writer', 
                             'OMDB_Actors', 'OMDB_Language', 'OMDB_Country', 'OMDB_Metascore', 'OMDB_imdbRating',
                             'OMDB_imdbVotes', 'OMDB_BoxOffice', 'OMDB_Production', 'ReleaseYear', 'ReleaseMonth']]

In [3]:
movies_df.head()

,Movie,ProductionBudget,DomesticGross,WorldwideGross,OMDB_Title,OMDB_Rated,OMDB_Runtime,OMDB_Genre,OMDB_Director,OMDB_Writer,OMDB_Actors,OMDB_Language,OMDB_Country,OMDB_Metascore,OMDB_imdbRating,OMDB_imdbVotes,OMDB_BoxOffice,OMDB_Production,ReleaseYear,ReleaseMonth
0,Avatar: The Way of Water,460000000,684075767,2319591720,Avatar: The Way of Water,teens,192.0,"Action, Adventure, Fantasy",James Cameron,"James Cameron, Rick Jaffa, Amanda Silver","Sam Worthington, Zoe Saldana, Sigourney Weaver",English,United States,67.0,7.6,466460.0,684075767.0,NaN,2022.0,12.0
1,Avengers: Endgame,400000000,858373000,2788912285,Avengers: Endgame,teens,181.0,"Action, Adventure, Drama","Anthony Russo, Joe Russo","Christopher Markus, Stephen McFeely, Stan Lee","Robert Downey Jr., Chris Evans, Mark Ruffalo","English, Japanese, Xhosa, German",United States,78.0,8.4,1223491.0,858373000.0,NaN,2019.0,4.0
2,Pirates of the Caribbean: On Stranger Tides,379000000,241071802,1045713802,Pirates of the Caribbean: On Stranger Tides,teens,136.0,"Action, Adventure, Fantasy",Rob Marshall,"Ted Elliott, Terry Rossio, Stuart Beattie","Johnny Depp, Pen√©lope Cruz, Ian McShane","English, Spanish","United States, United Kingdom",45.0,6.6,552123.0,241071802.0,NaN,2011.0,5.0
3,Avengers: Age of Ultron,365000000,459005868,1395316979,Avengers: Age of Ultron,teens,141.0,"Action, Adventure, Sci-Fi",Joss Whedon,"Joss Whedon, Stan Lee, Jack Kirby","Robert Downey Jr., Chris Evans, Mark Ruffalo","English, Korean",United States,66.0,7.3,902827.0,459005868.0,NaN,2015.0,5.0
4,Fast X,340000000,145960660,714414576,Fast X,teens,141.0,"Action, Adventure, Crime",Louis Leterrier,"Dan Mazeau, Justin Lin, Zach Dean","Vin Diesel, Michelle Rodriguez, Jason Statham",English,"United States, China, Japan",56.0,5.8,101452.0,145960660.0,NaN,2023.0,5.0

In [4]:
directors_df.head()

,Director,Instances,Total_Box_Office,Total_Production_Budget,Total_Metascore,Total_IMDB_Rating,Average_Box_Office,Average_IMDB_Rating,Success_Metric
0,James Cameron,8,2.673746e+09,1190400000,593.0,63.3,3.342183e+08,7.912500,14.596865
1,Anthony Russo,8,NaN,1426000000,491.0,57.4,NaN,7.175000,NaN
2,Joe Russo,8,NaN,1426000000,491.0,57.4,NaN,7.175000,NaN
3,Rob Marshall,6,7.888876e+08,760200000,364.0,39.5,1.314813e+08,6.583333,9.212959
4,Joss Whedon,5,1.756751e+09,714000000,352.0,38.9,3.513501e+08,7.780000,14.807003

# Pull in Director Average Box Office, IMDB Rating, and Combined Score

In [5]:
# Loop through every row of the movies_df
for index, row in movies_df.iterrows():
    movie_directors = row['OMDB_Director']
    # Only take action if the directors cell is populated with a string
    if isinstance(movie_directors, str) and movie_directors != "" :
        # Convert the comma separated list of directors into a list
        director_list = movie_directors.split(", ")
        # Set lists to store the ratings for a given row
        boxes = []
        ratings = []
        scores = []
        # Iterate through the each director in the lsit
        for d in director_list:
            # Collect the values for the given director
            d_box = directors_df.loc[directors_df['Director'] == d, 'Average_Box_Office'].iloc[0]
            d_rating = directors_df.loc[directors_df['Director'] == d, 'Average_IMDB_Rating'].iloc[0]
            d_score = directors_df.loc[directors_df['Director'] == d, 'Success_Metric'].iloc[0]

            # Only populate the list if a number (i.e., not NaN) to avoid creating NaN if 1 out of 6 is NaN
            if d_box > 0: 
                boxes.append(d_box)
            if d_rating > 0: 
                ratings.append(d_rating)
            if d_score > 0: 
                scores.append(d_score)
        # Populate the DataFrame with the average across the listed directors
        if boxes != []:
            directors_box = round(np.average(boxes),2)
            movies_df.loc[index,'Director_Avg_Box'] = directors_box
        if ratings != []:
            directors_rating = round(np.average(ratings),2)
            movies_df.loc[index,'Director_Avg_Rating'] = directors_rating
        if scores != []:
            directors_score = round(np.average(scores),2)
            movies_df.loc[index,'Director_Score'] = directors_score

movies_df.head()

,Movie,ProductionBudget,DomesticGross,WorldwideGross,OMDB_Title,OMDB_Rated,OMDB_Runtime,OMDB_Genre,OMDB_Director,OMDB_Writer,...,OMDB_Metascore,OMDB_imdbRating,OMDB_imdbVotes,OMDB_BoxOffice,OMDB_Production,ReleaseYear,ReleaseMonth,Director_Avg_Box,Director_Avg_Rating,Director_Score
0,Avatar: The Way of Water,460000000,684075767,2319591720,Avatar: The Way of Water,teens,192.0,"Action, Adventure, Fantasy",James Cameron,"James Cameron, Rick Jaffa, Amanda Silver",...,67.0,7.6,466460.0,684075767.0,NaN,2022.0,12.0,3.342183e+08,7.91,14.60
1,Avengers: Endgame,400000000,858373000,2788912285,Avengers: Endgame,teens,181.0,"Action, Adventure, Drama","Anthony Russo, Joe Russo","Christopher Markus, Stephen McFeely, Stan Lee",...,78.0,8.4,1223491.0,858373000.0,NaN,2019.0,4.0,NaN,7.18,NaN
2,Pirates of the Caribbean: On Stranger Tides,379000000,241071802,1045713802,Pirates of the Caribbean: On Stranger Tides,teens,136.0,"Action, Adventure, Fantasy",Rob Marshall,"Ted Elliott, Terry Rossio, Stuart Beattie",...,45.0,6.6,552123.0,241071802.0,NaN,2011.0,5.0,1.314813e+08,6.58,9.21
3,Avengers: Age of Ultron,365000000,459005868,1395316979,Avengers: Age of Ultron,teens,141.0,"Action, Adventure, Sci-Fi",Joss Whedon,"Joss Whedon, Stan Lee, Jack Kirby",...,66.0,7.3,902827.0,459005868.0,NaN,2015.0,5.0,3.513501e+08,7.78,14.81
4,Fast X,340000000,145960660,714414576,Fast X,teens,141.0,"Action, Adventure, Crime",Louis Leterrier,"Dan Mazeau, Justin Lin, Zach Dean",...,56.0,5.8,101452.0,145960660.0,NaN,2023.0,5.0,1.081561e+08,6.31,8.48

# Pull in Writer Average Box Office, IMDB Rating, and Combined Score

In [6]:
# Loop through every row of the movies_df
for index, row in movies_df.iterrows():
    movie_writers = row['OMDB_Writer']
    # Only take action if the directors cell is populated with a string
    if isinstance(movie_writers, str) and movie_writers != "" :
        # Convert the comma separated list of directors into a list
        writer_list = movie_writers.split(", ")
        # Set lists to store the ratings for a given row
        boxes = []
        ratings = []
        scores = []
        # Iterate through the each director in the lsit
        for w in writer_list:
            # Collect the values for the given director
            w_box = writers_df.loc[writers_df['Writer'] == w, 'Average_Box_Office'].iloc[0]
            w_rating = writers_df.loc[writers_df['Writer'] == w, 'Average_IMDB_Rating'].iloc[0]
            w_score = writers_df.loc[writers_df['Writer'] == w, 'Success_Metric'].iloc[0]

            # Only populate the list if a number (i.e., not NaN) to avoid creating NaN if 1 out of 6 is NaN
            if w_box > 0: 
                boxes.append(w_box)
            if w_rating > 0: 
                ratings.append(w_rating)
            if w_score > 0: 
                scores.append(w_score)
        # Populate the DataFrame with the average across the listed directors
        if boxes != []:
            writers_box = round(np.average(boxes),2)
            movies_df.loc[index,'Writer_Avg_Box'] = writers_box
        if ratings != []:
            writers_rating = round(np.average(ratings),2)
            movies_df.loc[index,'Writer_Avg_Rating'] = writers_rating
        if scores != []:
            writers_score = round(np.average(scores),2)
            movies_df.loc[index,'Writer_Score'] = writers_score

movies_df.head()

,Movie,ProductionBudget,DomesticGross,WorldwideGross,OMDB_Title,OMDB_Rated,OMDB_Runtime,OMDB_Genre,OMDB_Director,OMDB_Writer,...,OMDB_BoxOffice,OMDB_Production,ReleaseYear,ReleaseMonth,Director_Avg_Box,Director_Avg_Rating,Director_Score,Writer_Avg_Box,Writer_Avg_Rating,Writer_Score
0,Avatar: The Way of Water,460000000,684075767,2319591720,Avatar: The Way of Water,teens,192.0,"Action, Adventure, Fantasy",James Cameron,"James Cameron, Rick Jaffa, Amanda Silver",...,684075767.0,NaN,2022.0,12.0,3.342183e+08,7.91,14.60,2.850750e+08,7.33,13.03
1,Avengers: Endgame,400000000,858373000,2788912285,Avengers: Endgame,teens,181.0,"Action, Adventure, Drama","Anthony Russo, Joe Russo","Christopher Markus, Stephen McFeely, Stan Lee",...,858373000.0,NaN,2019.0,4.0,NaN,7.18,NaN,4.218914e+08,7.16,15.53
2,Pirates of the Caribbean: On Stranger Tides,379000000,241071802,1045713802,Pirates of the Caribbean: On Stranger Tides,teens,136.0,"Action, Adventure, Fantasy",Rob Marshall,"Ted Elliott, Terry Rossio, Stuart Beattie",...,241071802.0,NaN,2011.0,5.0,1.314813e+08,6.58,9.21,1.762009e+08,6.81,10.33
3,Avengers: Age of Ultron,365000000,459005868,1395316979,Avengers: Age of Ultron,teens,141.0,"Action, Adventure, Sci-Fi",Joss Whedon,"Joss Whedon, Stan Lee, Jack Kirby",...,459005868.0,NaN,2015.0,5.0,3.513501e+08,7.78,14.81,3.273985e+08,6.71,13.71
4,Fast X,340000000,145960660,714414576,Fast X,teens,141.0,"Action, Adventure, Crime",Louis Leterrier,"Dan Mazeau, Justin Lin, Zach Dean",...,145960660.0,NaN,2023.0,5.0,1.081561e+08,6.31,8.48,9.776042e+07,5.97,7.81

# Pull in Actor/Actress Average Box Office, IMDB Rating, and Combined Score

In [7]:
# Loop through every row of the movies_df
for index, row in movies_df.iterrows():
    movie_actors = row['OMDB_Actors']
    # Only take action if the directors cell is populated with a string
    if isinstance(movie_actors, str) and movie_actors != "" :
        # Convert the comma separated list of directors into a list
        actor_list = movie_actors.split(", ")
        # Set lists to store the ratings for a given row
        boxes = []
        ratings = []
        scores = []
        # Iterate through the each director in the lsit
        for w in actor_list:
            # Collect the values for the given director
            a_box = actors_df.loc[actors_df['Actor'] == w, 'Average_Box_Office'].iloc[0]
            a_rating = actors_df.loc[actors_df['Actor'] == w, 'Average_IMDB_Rating'].iloc[0]
            a_score = actors_df.loc[actors_df['Actor'] == w, 'Success_Metric'].iloc[0]

            # Only populate the list if a number (i.e., not NaN) to avoid creating NaN if 1 out of 6 is NaN
            if a_box > 0: 
                boxes.append(w_box)
            if a_rating > 0: 
                ratings.append(w_rating)
            if a_score > 0: 
                scores.append(w_score)
        # Populate the DataFrame with the average across the listed directors
        if boxes != []:
            actors_box = round(np.average(boxes),2)
            movies_df.loc[index,'Actor_Avg_Box'] = actors_box
        if ratings != []:
            actors_rating = round(np.average(ratings),2)
            movies_df.loc[index,'Actor_Avg_Rating'] = actors_rating
        if scores != []:
            actors_score = round(np.average(scores),2)
            movies_df.loc[index,'Actor_Score'] = actors_score

movies_df.head()

,Movie,ProductionBudget,DomesticGross,WorldwideGross,OMDB_Title,OMDB_Rated,OMDB_Runtime,OMDB_Genre,OMDB_Director,OMDB_Writer,...,ReleaseMonth,Director_Avg_Box,Director_Avg_Rating,Director_Score,Writer_Avg_Box,Writer_Avg_Rating,Writer_Score,Actor_Avg_Box,Actor_Avg_Rating,Actor_Score
0,Avatar: The Way of Water,460000000,684075767,2319591720,Avatar: The Way of Water,teens,192.0,"Action, Adventure, Fantasy",James Cameron,"James Cameron, Rick Jaffa, Amanda Silver",...,12.0,3.342183e+08,7.91,14.60,2.850750e+08,7.33,13.03,NaN,NaN,NaN
1,Avengers: Endgame,400000000,858373000,2788912285,Avengers: Endgame,teens,181.0,"Action, Adventure, Drama","Anthony Russo, Joe Russo","Christopher Markus, Stephen McFeely, Stan Lee",...,4.0,NaN,7.18,NaN,4.218914e+08,7.16,15.53,NaN,NaN,NaN
2,Pirates of the Caribbean: On Stranger Tides,379000000,241071802,1045713802,Pirates of the Caribbean: On Stranger Tides,teens,136.0,"Action, Adventure, Fantasy",Rob Marshall,"Ted Elliott, Terry Rossio, Stuart Beattie",...,5.0,1.314813e+08,6.58,9.21,1.762009e+08,6.81,10.33,NaN,NaN,NaN
3,Avengers: Age of Ultron,365000000,459005868,1395316979,Avengers: Age of Ultron,teens,141.0,"Action, Adventure, Sci-Fi",Joss Whedon,"Joss Whedon, Stan Lee, Jack Kirby",...,5.0,3.513501e+08,7.78,14.81,3.273985e+08,6.71,13.71,NaN,NaN,NaN
4,Fast X,340000000,145960660,714414576,Fast X,teens,141.0,"Action, Adventure, Crime",Louis Leterrier,"Dan Mazeau, Justin Lin, Zach Dean",...,5.0,1.081561e+08,6.31,8.48,9.776042e+07,5.97,7.81,NaN,NaN,NaN

In [8]:
movies_df.to_csv("./Resources/movies_people2numbers.csv")